name: build-test-deb-package

on:
  push:
    paths:
    - ".github/workflows/build-test-deb-package.yml"

env:
  PACKAGE_NAME: auto-cpulimit
  VERSION: "0.1"
  REVISION: "1"
  ARCHITECTURE: all

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure the environment
        id: configure_environment
        run: |
          echo "DPKG_DEP_NAME=${{ env.PACKAGE_NAME }}_${{ env.VERSION }}-${{ env.REVISION }}_${{ env.ARCHITECTURE }}" >> $GITHUB_ENV
