name: build-test-deb-package

on: push

env:
  PACKAGE_NAME: auto-cpulimit
  VERSION: "0.1"
  REVISION: "1"
  ARCHITECTURE: amd64

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure the environment
        id: configure_environment
        run: |
          echo "DPKG_DEP_NAME=${{ env.PACKAGE_NAME }}_${{ env.VERSION }}-${{ env.REVISION }}_${{ env.ARCHITECTURE }}" >> $GITHUB_ENV

      - name: create the folder structure
        run: |
          mkdir -p ${{ env.DPKG_DEP_NAME }}/usr/local/bin

          cp acl.sh ${{ env.DPKG_DEP_NAME }}/usr/local/bin
          cp -r DEBIAN ${{ env.DPKG_DEP_NAME }}

      - name: build the deb package
        run: |
          ls -R ${{ env.DPKG_DEP_NAME }}
          dpkg-deb --build --root-owner-group ${{ env.DPKG_DEP_NAME }}

      - name: install the deb package
        run: |
          sudo dpkg -i ${{ env.DPKG_DEP_NAME }}.deb
          sudo apt -f install
          dpkg -l

      - name: run a package command
        run: |
          sudo ${{ env.PACKAGE_NAME }} --help
