name: build-test-deb-package

on: push

env:
  PACKAGE_NAME: auto-cpulimit
  VERSION: "0.1"
  ARCHITECTURE: all

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure the environment
        id: configure_environment
        run: |
          echo "DPKG_DEB_NAME=${{ env.PACKAGE_NAME }}_${{ env.VERSION }}_${{ env.ARCHITECTURE }}" >> $GITHUB_ENV

      - name: build the deb package
        run: |
          ls -R
          dpkg-buildpackage -d -uc -us

      - name: install the deb package
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install ./${{ env.DPKG_DEB_NAME }}.deb
          dpkg -l

      - name: run a package command
        run: |
          sudo ${{ env.PACKAGE_NAME }} --help
