name: ci

on:
  push:
    paths:
    - ".github/workflows/ci.yml"
    - "acl.sh"

jobs:
  test-sh:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: auto-cpulimit sh
        run: |
          ./acl.sh
