name: compile-sh-to-executable

on: push

env:
  PACKAGE_NAME: auto-cpulimit
  VERSION: "0.1"
  ARCHITECTURE: all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:neurobin/ppa
          sudo apt-get update
          sudo apt-get install shc

      - name: compile shell script to executable
        run: |
          shc -f ./acl.sh
          ls
