name: compile-sh-to-executable

on: push

env:
  NAME_OF_EXECUTABLE: auto-cpulimit
  VERSION: "0.1"
  ARCHITECTURE: all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:neurobin/ppa
          sudo apt-get update
          sudo apt-get install shc

      - name: compile shell script to executable
        run: |
          shc -v -f ./acl.sh
          ls
          mv acl.sh.x ${{ env.NAME_OF_EXECUTABLE }}

      - name: test executable
        run: |
          ./NAME_OF_EXECUTABLE --help
