name: release

on:
  push:
    paths:
    - ".github/workflows/release.yml"
    tags:
      - 'v*'

env:
  NAME_OF_PROGRAM: auto-cpulimit

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:neurobin/ppa
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install shc
          sudo apt install dos2unix

      - name: get the current version release tag
        id: get_release_tag
        run: |
          pushed_tag=${GITHUB_REF/refs\/tags\//}
          echo "[DEBUG] _version_release_tag=$pushed_tag"
          echo "VERSION_RELEASE_TAG=$pushed_tag" >> $GITHUB_ENV

      - name: compile shell script to binary
        run: |
          shc -v -f ./helloworld.sh && mv helloworld.sh.x helloworld
          shc -v -f ./acl.sh && mv acl.sh.x ${{ env.NAME_OF_PROGRAM }}

      - name: upload binary
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.NAME_OF_PROGRAM }}-binary-${{ env.VERSION_RELEASE_TAG }}
          path: ${{ env.NAME_OF_PROGRAM }}

      - name: download binary
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.NAME_OF_PROGRAM }}-binary-${{ env.VERSION_RELEASE_TAG }}

      - name: upload binary to github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.G_TOKEN }}
          file: ${{ env.NAME_OF_PROGRAM }}
          asset_name: ${{ env.NAME_OF_PROGRAM }}-binary-${{ env.VERSION_RELEASE_TAG }}
          tag: ${{ env.VERSION_RELEASE_TAG }}
          prerelease: true
